package com.repzone.domain.model

data class ProductFlatModel(
    val productId: Long,
    val sku: String,
    val productName: String,
    val unitId: Long,
    val unitName: String,
    val multiplier: Long,
    val price: Double,
    val weight: Double?,
    val vat: Long,
    val tags: String,
    val brandId: Long,
    val brandName: String,
    val groupId: Long,
    val groupName: String,
    val stock: Double,
    val orderStock: Double,
    val barcode: String,
    val displayOrder: Long,
    val photoPath: String,
    val unitDisplayOrder: Long,
    val color: String,
    val vanStock: Double,
    val brandPhotoPath: String,
    val groupPhotoPath: String,
    val minimumOrderQuantity: Long,
    val maxOrderQuantity: Long,
    val orderQuantityFactor: Long,
    val description: String,
    val transitStock: Double,
    val pendingStock: Double,
    val reservedStock: Double,
    val showTransitStock: Long,
    val showAvailableStock: Long,
    val manufacturerId: Long?
)
