package com.repzone.domain.model

data class SyncProductModel(
    val Id: Long,
    val BrandId: Long?,
    val BrandName: String?,
    val BrandPhotoPath: String?,
    val CloseToReturns: Long?,
    val CloseToSales: Long?,
    val Color: String?,
    val Description: String?,
    val DisplayOrder: Long?,
    val GroupId: Long?,
    val GroupName: String?,
    val GroupPhotoPath: String?,
    val IsVisible: Long?,
    val ManufacturerId: Long?,
    val MaximumOrderQuantity: Long?,
    val MinimumOrderQuantity: Long?,
    val ModificationDateUtc: Long?,
    val Name: String?,
    val OrderQuantityFactor: Long?,
    val OrganizationId: Long?,
    val OrganizationIds: String?,
    val PhotoPath: String?,
    val RecordDateUtc: Long?,
    val Shared: Long?,
    val Sku: String?,
    val State: Long?,
    val Tags: String?,
    val TenantId: Long?,
    val Vat: Double?,
)
