package com.repzone.domain.model

data class SyncCustomerModel(
    val Id: Long,
    val Balance: Double?,
    val Blocked: Long?,
    val CheckRiskDispatch: Long?,
    val CheckRiskOnBalance: Long?,
    val CheckRiskOrder: Long?,
    val CheckRiskOrderProposal: Long?,
    val Code: String?,
    val DamagedReturnPriceType: Long?,
    val DispatchMonitoringAction: Long?,
    val GroupId: Long?,
    val GroupName: String?,
    val GroupPhotoPath: String?,
    val IconIndex: Long?,
    val InvoiceMonitoringAction: Long?,
    val IsECustomer: Long?,
    val IsVatExempt: Long?,
    val IsVisible: Long?,
    val Name: String?,
    val OrderMonitoringAction: Long?,
    val OrderProposalMonitoringAction: Long?,
    val OrganizationCode: String?,
    val OrganizationId: Long?,
    val OrganizationName: String?,
    val ParentId: Long?,
    val PaymentPlanId: Long?,
    val PhotoPath: String?,
    val ReturnPriceType: Long?,
    val Risk: Double?,
    val RiskDueDay: Long?,
    val State: Long?,
    val Tags: String?,
    val TaxNumber: String?,
    val TaxOffice: String?,
)