package com.repzone.core.enums

enum class ModuleProductIdsEnum(val value : Int) {
    CUSTOMMOBILEFORMS(8),
    DIGITALCONTENTSHARING(11),
    MESSAGINGANDCHAT(12),
    EAGLEEYEANDLOCATIONTRACKING(13),
    REPORTS(15),
    ORDERS(19),
    BUSINESSINTELLIGENCE(22),
    TASKMANAGEMENT(23),
    ATTENDANCETRACKING(24),
    INVOICESANDEINVOICES(26),
    PAYMENTCOLLECTION(29),
    DIGITALPRODUCTCATALOG(31),
    GEOFENCINGANDROUTETRACKING(32),
    DISPATCHES(36),
    QUICKACCESS(37),
    GAMIFICATION(38),
    CRMOPERATIONS(39),
    PRODUCTALLOCATION(40),
    VISIT(41)
}