package com.repzone.core.enums

enum class PriceListRuleProperty(val value: Int) {
    CUSTOMERID(14),
    CUSTOMERGROUPID(27),
    CUSTOMERPARENTID(13),
    CUSTOMERCUSTOMFIELDID(25),
    CUSTOMERDYNAMICLISTID(19),
    CUSTOMERORGANIZATIONID(23),
    REPRESENTATIVEID(21),
    REPRESENTATIVEGROUPID(28),
    REPRESENTATIVECUSTOMFIELDID(26),
    REPRESENTDYNAMICLISTID(20),
    REPRESENTATIVEORGANIZATIONID(22)
}