package com.repzone.sync.model

// Job tiplerini burada tasiyabiliriz Haluk ile gorusecegiz

enum class SyncJobType {
    PRODUCTS,
    PRODUCTS_GROUP,
    ROUTE,
    CUSTOMERS,
    CUSTOMERS_GROUP,
    CUSTOMERS_EMAIL,
    CUSTOMERS_PRICE_PARAMETERS,
    CUSTOMERS_GROUP_PRICE,
    TABLE_REPLICATION,
    COMMON_MODULES,
    COMMON_MODULES_REASONS,
    COMMON_DOCUMENT_MAPS,
    COMMON_DYNAMIC_PAGES,
    FORM,
    FORM_MANDATORY,
    EXTRA_TABLE,
    STOCK,
    EXTRATABLE_REPLICATION_DOCUMENTORGANIZATIONS
}

enum class SyncJobGroup{
    NONE,
    DOCUMENT,
    CUSTOMER,
    PRODUCT,
    FORMS
}